/*globals define, WebGMEGlobal*/

/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Tue Dec 03 2024 17:04:59 GMT-0600 (Central Standard Time).
 */

define(['plotly',
    'blob/BlobClient',
    'css!./styles/ResultsVizWidget.css'], function (Plotly,BlobClient) {
    'use strict';

    var WIDGET_CLASS = 'results-viz';

    function ResultsVizWidget(logger, container, client) {
        this._logger = logger.fork('Widget');

        this._el = container;
        
        this._client = client;

        this.nodes = {};
        this._initialize();

        this._blobClient = new BlobClient({ logger: this._logger.fork('BlobClient') });

        this._logger.debug('ctor finished');
    }

    ResultsVizWidget.prototype._initialize = function () {
        var width = this._el.width(),
            height = this._el.height(),
            self = this;

        // set widget class
        this._el.addClass(WIDGET_CLASS);

        // Create a dummy header
        this._el.append('<h3>NS-MDP Experiment Results Visualization</h3>');

        this._el.append('<div id="plot-container" style="width:100%; height:400px;"></div>');
        
        this.activeId = null;
        this.datas = {};
        this.logs = {};

        


        // Registering to events can be done with jQuery (as normal)
        this._el.on('dblclick', function (event) {
            event.stopPropagation();
            event.preventDefault();
            self.onBackgroundDblClick();
        });
    };

    ResultsVizWidget.prototype.onWidgetContainerResize = function (width, height) {
        this._logger.debug('Widget is resizing...');
    };

    // Adding/Removing/Updating items
    ResultsVizWidget.prototype.addNode = function (desc) {
        if (desc) {
            // Add node to a table of nodes
            var node = document.createElement('div'),
                label = 'children';

            if (desc.childrenIds.length === 1) {
                label = 'child';
            }

            this.nodes[desc.id] = desc;
            node.innerHTML = 'Adding node "' + desc.name + '" (click to view). It has ' +
                desc.childrenIds.length + ' ' + label + '.';
            
            // Place holder log function... 

     
            // Fetch node data asynchronously

            var node_obj = this._client.getNode(desc.id);

            this.loadNodeData(desc)
            .then((data) => {
                console.log('Loaded data for node:', desc.id, data);
                // Pass the loaded data to plotLogs
                this.plotLogs(data, desc);
            })
            .catch((error) => {
                console.error('Error loading data for node:', desc.id, error);
            });

            
            
            this._el.append(node);
            node.onclick = this.onNodeClick.bind(this, desc.id);
        }
    };

    ResultsVizWidget.prototype.removeNode = function (gmeId) {
        var desc = this.nodes[gmeId];
        this._el.append('<div>Removing node "' + desc.name + '"</div>');
        delete this.nodes[gmeId];
    };

    ResultsVizWidget.prototype.updateNode = function (desc) {
        if (desc) {
            this._logger.debug('Updating node:', desc);
            this._el.append('<div>Updating node "' + desc.name + '"</div>');
    
            // Reload node data and update the plot
            this.loadNodeData(desc)
                .then((data) => {
                    console.log('Updated data for node:', desc.id, data);
                    this.plotLogs(data, desc); // Replot with the updated data
                })
                .catch((error) => {
                    console.error('Error updating data for node:', desc.id, error);
                });
        }
    };
    /***************************** Data Load */
    
    ResultsVizWidget.prototype.loadNodeData = function (desc) {
        // Load JSON experiment data from the node
        var node_obj = this._client.getNode(desc.id);
        var results_hash = node_obj.getAttribute('exp_result');

        console.log('Node:', node_obj);
        console.log('Results Hash:', results_hash);

        if (results_hash) {
            return this._blobClient.getObjectAsJSON(results_hash)
                .then((jsonData) => {
                    console.log('Fetched JSON Data:', jsonData);
                    return jsonData; // Return the resolved JSON data
                })
                .catch((error) => {
                    console.error('Error fetching JSON data:', error);
                    throw error; // Re-throw the error for the caller to handle
                });
        } else {
            // Return a rejected Promise if results_hash is missing
            return Promise.reject(new Error('Results hash is undefined or null for node: ' + desc.id));
        }

    };

    ResultsVizWidget.prototype.plotLogs = function (data, desc) {
        var self = this;
    
        console.log('Plotting logs:', data);

        console.log("reward",data.episode_rewards);
    
        // Extract episode_rewards from the data
        var episode_rewards = data.episode_rewards;
    
        if (!episode_rewards || episode_rewards.length === 0) {
            console.error('No episode rewards data available to plot');
            return;
        }
    
        console.log('Episode Rewards:', episode_rewards);
    
        self.clearPlot();
    
        // Generate the x-axis values (episode numbers)
        var episode_numbers = Array.from({ length: episode_rewards.length }, (_, i) => i + 1);
    
        // Define data for the line graph
        var plotData = [
            {
                x: episode_numbers, // X-axis values (episode numbers)
                y: episode_rewards, // Y-axis values (episode rewards)
                type: 'bar', // Line plot
                mode: 'lines+markers', // Line plot with markers
                name: 'Episode Rewards'
            }
        ];
    
        // Define layout for the plot
        var layout = {
            title: 'Episode Rewards: ' + desc.name,
            xaxis: { title: 'Episode Number' },
            yaxis: { title: 'Cumulative Episode Reward' },
            showlegend: true
        };
    
        // Render the plot using Plotly
        Plotly.newPlot('plot-container', plotData, layout);
    };
    
    

    ResultsVizWidget.prototype.clearPlot = function () {
        if (this._el) {
            // Clear the plot container
            this._el.find('#plot-container').empty();
            // Add back the plot div
            this._el.find('#plot-container').append('<div id="plot"></div>');
        };
    };
    /* * * * * * * * Visualizer event handlers * * * * * * * */

    ResultsVizWidget.prototype.onNodeClick = function (/*id*/) {
        // This currently changes the active node to the given id and
        // this is overridden in the controller.
    };

    ResultsVizWidget.prototype.onBackgroundDblClick = function () {
        this._el.append('<div>Background was double-clicked!!</div>');
    };

    /* * * * * * * * Visualizer life cycle callbacks * * * * * * * */
    ResultsVizWidget.prototype.destroy = function () {
    };

    ResultsVizWidget.prototype.onActivate = function () {
        this._logger.debug('ResultsVizWidget has been activated');
    };

    ResultsVizWidget.prototype.onDeactivate = function () {
        this._logger.debug('ResultsVizWidget has been deactivated');
    };

    return ResultsVizWidget;
});
